import test from 'node:test';import assert from 'node:assert/strict';
import {books,verses,parsePassage,rangeCount,rangeLabel,deriveStats,serialize,deserialize,type Reading} from './domain';
test('canonical metadata is sequential and complete',()=>{assert.equal(books.length,66);assert.equal(verses.length,31102);assert.equal(verses[0].osisId,'Gen.1.1');assert.equal(verses.at(-1)?.osisId,'Rev.22.21');for(const [i,v] of verses.entries())assert.equal(v.id,i);});
test('common references and abbreviations',()=>{for(const input of ['Romans 8:1-17','Rom 8:1–17'])assert.equal(rangeCount(parsePassage(input)),17);assert.equal(rangeCount(parsePassage('Romans 8')),39);assert.equal(rangeCount(parsePassage('Romans 8:28-9:5')),17);assert.equal(rangeCount(parsePassage('Psalm 23; John 10:1-18')),24);assert.equal(rangeCount(parsePassage('Matthew 5-7')),111);assert.equal(rangeCount(parsePassage('Genesis')),1533);assert.equal(rangeCount(parsePassage('1 Corinthians 12-14')),84);assert.equal(rangeLabel(parsePassage('Song of Solomon 1')[0]),'Song of Solomon 1');assert.equal(rangeCount(parsePassage('Genesis 1:1-Revelation 22:21')),31102);});
test('invalid references fail with useful errors',()=>{for(const s of ['Romans 17','John 3:99','Genesis 0','Foo 3','Romans 8:17-1','Romans 8;','Romans 8:0','Romans 8-',''])assert.throws(()=>parsePassage(s));});
test('overlapping passages count a verse once per session',()=>{const ranges=parsePassage('Rom 8:1-17; Romans 8:10-20');assert.equal(rangeCount(ranges),20);const r:Reading={id:'a',startedAt:'2026-09-01T12:00:00.000Z',createdAt:'2026-09-01T12:00:00.000Z',updatedAt:'2026-09-01T12:00:00.000Z',notes:'Notes',originalInput:'Rom 8:1-20',ranges};const stats=deriveStats([r]);assert.equal(stats[ranges[0].start+12].count,1);assert.deepEqual(deserialize(serialize([r])),[r]);assert.equal(deriveStats([])[ranges[0].start].count,0);const edited={...r,ranges:parsePassage('John 1')};assert.equal(deriveStats([edited])[ranges[0].start].count,0);});
test('import rejects malformed, duplicate, and foreign data',()=>{assert.throws(()=>deserialize({format:'bad'}));const r:Reading={id:'a',startedAt:'2026-09-01T12:00:00.000Z',createdAt:'2026-09-01T12:00:00.000Z',updatedAt:'2026-09-01T12:00:00.000Z',notes:'',originalInput:'John 1',ranges:parsePassage('John 1')};assert.throws(()=>deserialize(serialize([r,r])));assert.throws(()=>deserialize({...serialize([r]),versification:'other'}));assert.throws(()=>deserialize(serialize([{...r,startedAt:'oops'}])));});

test('every book and chapter resolves to its canonical bounds',()=>{for(const b of books){assert.deepEqual(parsePassage(b.name),[{start:b.start,end:b.end}]);for(const [i,ch] of b.chapters.entries()){assert.deepEqual(parsePassage(`${b.name} ${i+1}`),[{start:ch.start,end:ch.end}]);assert.equal(rangeCount(parsePassage(`${b.name} ${i+1}:1-${ch.count}`)),ch.count);}}});
test('range shorthand, alternative names, and book boundaries',()=>{assert.equal(rangeCount(parsePassage('1 Cor 12-14')),84);assert.equal(rangeCount(parsePassage('I Corinthians 12-14')),84);assert.equal(rangeCount(parsePassage('Song of Songs 1')),17);assert.equal(rangeCount(parsePassage('Genesis 50:26-Exodus 1:2')),3);assert.equal(rangeCount(parsePassage('Rom 8:1-17; 8:10-20')),20);assert.equal(rangeCount(parsePassage('John 3:16; John 3:16')),1);});
import {bucket} from './domain';
test('recency and frequency use explicit buckets',()=>{const now=Date.parse('2026-10-04T12:00:00Z');assert.equal(bucket({count:0,first:null,last:null},'recency',now),0);for(const [days,expected] of [[0,6],[2,5],[15,4],[60,3],[200,2],[400,1]])assert.equal(bucket({count:1,first:null,last:new Date(now-days*86400000).toISOString()},'recency',now),expected);for(const [count,expected] of [[0,0],[1,1],[3,2],[8,3],[20,4],[30,5],[100,6]])assert.equal(bucket({count,first:null,last:null},'frequency'),expected);});
import {layoutGeometry,hitTest} from './layout';
test('flow responds to width and fixed grid preserves canonical coordinates',()=>{const scope={start:320,end:639};const flow=layoutGeometry(scope,400,4,false);assert.equal(flow.columns,100);assert.equal(flow.offset,320);assert.equal(hitTest(0,0,scope,flow.columns,flow.offset,4),320);const a=layoutGeometry(scope,400,4,true),b=layoutGeometry(scope,1200,4,true);assert.deepEqual(a,b);assert.equal(a.columns,160);assert.equal(a.height,8);assert.equal(hitTest(4,4,scope,a.columns,a.offset,4),481);assert.equal(hitTest(3,0,scope,a.columns,a.offset,4),null);assert.equal(hitTest(-1,0,scope,a.columns,a.offset,4),null);const partial=layoutGeometry({start:322,end:330},400,4,true);assert.equal(hitTest(0,0,{start:322,end:330},partial.columns,partial.offset,4),null);});
