import {DEFAULT_JOURNAL_ID,defaultJournal,migrateLegacyReadings,type Journal,type JournalReading,type JournalState} from './journals';
export interface ReadingRepository {load():Promise<JournalState>;replace(state:JournalState):Promise<void>;selectJournal(id:string):Promise<void>;}
const connect=()=>new Promise<IDBDatabase>((resolve,reject)=>{
 const request=indexedDB.open('jot-and-tittle',2);
 request.onupgradeneeded=event=>{const db=request.result;const tx=request.transaction!;if(event.oldVersion<1)db.createObjectStore('readings',{keyPath:'id'});if(event.oldVersion<2){const journals=db.createObjectStore('journals',{keyPath:'id'});journals.put(defaultJournal());const settings=db.createObjectStore('settings',{keyPath:'id'});settings.put({id:'activeJournalId',value:DEFAULT_JOURNAL_ID});const cursor=tx.objectStore('readings').openCursor();cursor.onsuccess=()=>{const entry=cursor.result;if(entry){entry.update(migrateLegacyReadings([entry.value])[0]);entry.continue();}};}};
 request.onsuccess=()=>{const db=request.result;db.onversionchange=()=>db.close();resolve(db);};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('Close other Jot & Tittle tabs to upgrade your local journals.'));
});
export const repository:ReadingRepository={
 async load(){const db=await connect();return new Promise((resolve,reject)=>{const tx=db.transaction(['readings','journals','settings'],'readonly');const readings=tx.objectStore('readings').getAll(),journals=tx.objectStore('journals').getAll(),setting=tx.objectStore('settings').get('activeJournalId');tx.oncomplete=()=>{db.close();const rows=journals.result as Journal[];rows.sort((a,b)=>a.id===DEFAULT_JOURNAL_ID?-1:b.id===DEFAULT_JOURNAL_ID?1:a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));resolve({readings:readings.result as JournalReading[],journals:rows,activeJournalId:rows.some(j=>j.id===setting.result?.value)?setting.result.value:rows[0].id});};tx.onerror=()=>{db.close();reject(tx.error);};tx.onabort=()=>{db.close();reject(tx.error);};});},
 async replace(state){const ids=new Set(state.journals.map(j=>j.id));const readingIds=new Set(state.readings.map(r=>r.id));if(ids.size!==state.journals.length||readingIds.size!==state.readings.length||state.readings.some(r=>!r.id)||state.journals.some(j=>!j.id))throw new Error('Journal and reading IDs must be present and unique.');if(!ids.has(state.activeJournalId)||state.readings.some(r=>!ids.has(r.journalId)))throw new Error('Readings must belong to an existing journal.');const db=await connect();return new Promise((resolve,reject)=>{const tx=db.transaction(['readings','journals','settings'],'readwrite');const readings=tx.objectStore('readings'),journals=tx.objectStore('journals');try{readings.clear();journals.clear();for(const r of state.readings)readings.put(r);for(const j of state.journals)journals.put(j);tx.objectStore('settings').put({id:'activeJournalId',value:state.activeJournalId});}catch(e){tx.abort();db.close();reject(e);return;}tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};tx.onabort=()=>{db.close();reject(tx.error||new Error('Storage operation aborted.'));};});},
 async selectJournal(id){const db=await connect();return new Promise((resolve,reject)=>{const tx=db.transaction(['settings','journals'],'readwrite');const request=tx.objectStore('journals').get(id);request.onsuccess=()=>{if(!request.result){tx.abort();return;}tx.objectStore('settings').put({id:'activeJournalId',value:id});};tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};tx.onabort=()=>{db.close();reject(tx.error||new Error('Journal not found.'));};});}
};
